### ISSUE TITLE
`getOneWeekPrices()` method.

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#10]
Basically this method will take the price documents of the last seven days. Note that it may be more than seven documents.

## Todo

- [x]  repository: add contract and implementation of `getOneWeekPrices()`
- [ ]  remote_datasource: add contract and implementation of `getOneWeekPrices()`
- [ ]  bloc: add event and states of `getOneWeekPrices()`
