### ISSUE TITLE
Implement kg denomination

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#12]
Basically, the app should allow the possibility of denominations (or appends, whatever) of kg/g/etc. for a specific type of produce. This though, may bring about a few problems but that is going to depend on how denominations are applied. Here are some (but not limited to) of the solutions:

1. Allow the creation of multiple of `Produce` of the same type, each with their own specific denomination. Relation between each other can be deduced by adding a new `relatedTo` field which keeps the ids of the same `Produce`.
e.g.
Sawi - RM4/kg
Sawi - RM0.10/g

2. Force a singular denomination for ALL of the produce. e.g. Forcing all `Produce` to use kg

3. Have each `Price` document have a specific denomination. This will definitely pose an issue to charts, where it expects to have a uniform scale.

@ahmadmuqry sila.

# Updates
kg denominations will be hard coded into the UI, meaning that as far as `Produce` or `Firestore` or `Graphs` or anything related to price is concerned, the price is set in kg.

## Todo

UI
- [x] `ProduceListCard` in `MainScreen` and `AddNewPriceScreen`
- [x] `Heading` in `ProduceScreen`
- [x] `currentProducePrice` text field in `CreateProduceScreen`
- [x] "Current Price" and "Previous Price" in `AddNewPriceSecondScreen` and `AddNewPriceThirdScreen`
