### ISSUE TITLE
Allow `TwoFieldsForm` to accept varying amount of fields.

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#13]
Currently will be up to four.

## Todo

- [x] Add enum
- [x] Add necessary variables and add to constructor
- [x] Rename `TwoFieldsForm` to `MultipleFieldsForm`
  - [x] Rename `TwoFieldsFormBloc` to `MultipleFieldsFormBloc`
  - [x] Rename states and events
- [x] Update props to have up to four of every variable.
- [x] Fix every client of `TwoFieldsForm`

Before and after renaming:
- [x] Test and see if I broke anything (I didn't)
- [x] Test and see if I broke anything (after rename)

Do:
- [x] Bloc methods 
- [x] `submitted` events.
    - [x] First Field
    - [x] Second Field
    - [x] Third Field
    - [x] Fourth Field
