### ISSUE TITLE
Update `RegisterScreen` to use `MultipleFormFields`

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#14]
With the implementation of #13 , `RegisterScreen` should utilise it rather than using the mixin approach.

## Todo

- [x] Change to `MultipleFormFields` of type `MultipleFormFields.fourField`
- [x] Update bloc methods
- [x] Test and see if I broke anything
