### ISSUE TITLE
Update `LargePriceChart` to be independent of `ProduceScreen`

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#20]
Basically extract `LargePriceChart` so it could be used in other screens.

## Todo
- [x] Remove dependence on `ProduceScreenBloc`, instead use enums.
- [x] Add a method to determine the `LargePriceChartType` based on the index of the tab bar
- [x] Added `LargePriceChartType` enums
