### ISSUE TITLE
`flutter_speed_dial_modified` is unable to be pushed to remote repo.

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#4]
I'm not sure why this is happening, and it is really bothering the workflow. Now, there are two possible solutions.

## Solutions

1. Remove `flutter_speed_dial_modified` from local and change it to a GitHub dependency. This has its issues though, mainly that it will be difficult to quickly see changes 
2. Take it in like a man

# Todo List

- [x] Remove from local
- [x] Push most recent updates
- [x] Depend on repo 
- [x] Close with `failure-overhaul`
