### ISSUE TITLE
Improvements on `getFirstTenProduce()` and `getNextTenProduce()` in `MainScreen` and `SearchScreen`

### ISSUE THREAD

**Issue by nazrinharris** [nazrinharris/farmhub#54]
Just some minor updates I in the case that `getFirstTenProduce()` retrieves an empty list. (This can happen when there is literally no `Produce` in the database, or an error)

The error in question happened when I updated `Produce` to have `lastUpdateTimeStamp`. There was an error when creating `Produce` objects. Because the `Produce` in the database didn't yet have the `lastUpdateTimeStamp` field. The error itself was a little bit hard to notice unless I set breakpoints for all exceptions.

### Todo
- [x] When `getFirstTenProduce()` returns an empty list, show a message indicating as such.
- [x] When the `lastPricesList` in `getNextTenProduce()` is empty, it should throw an `Exception`.
- [x] When scrolling to the end and getting the next ten produce, it should first check if `lastPricesList` is empty. If it is, it should throw an exception
- [x] In SearchScreen, when it receives an exception with the `PM_ERR_EMPTY_PREVIOUS_PRODUCE_LIST`, it should do nothing rather than show an error message
